#pragma once

#include "Player/PlayerActorBase.h"
#include "Util/IUseDimension.h"

namespace al {
class ComboCounter;
class FootPrintHolder;
class HitSensor;
class WaterSurfaceFinder;
}  // namespace al

class PlayerInfo;
class PlayerConst;
class PlayerInput;
class PlayerTrigger;
class HackCap;
class ActorDimensionKeeper;
class PlayerModelHolder;
class PlayerModelChangerHakoniwa;
class PlayerAnimator;
class PlayerColliderHakoniwa;
class PlayerPuppet;
class PlayerAreaChecker;
class PlayerOxygen;
class PlayerDamageKeeper;
class PlayerDemoActionFlag;
class PlayerCapActionHistory;
class PlayerCapManHeroEyesControl;
class PlayerContinuousJump;
class PlayerContinuousLongJump;
class PlayerCounterAfterUpperPunch;
class PlayerCounterForceRun;
class PlayerCounterIceWater;
class PlayerCounterQuickTurnJump;
class PlayerWallActionHistory;
class PlayerBindKeeper;
class PlayerCarryKeeper;
class PlayerEquipmentUser;
class PlayerHackKeeper;
class PlayerFormSensorCollisionArranger;
struct PlayerJumpMessageRequest;
class PlayerSandSinkAffect;
class PlayerSpinCapAttack;
class PlayerActionDiveInWater;
class PlayerEffect;
class PlayerEyeSensorHitHolder;
class PlayerPushReceiver;
class PlayerHitPush;
class PlayerExternalVelocity;
class PlayerJointControlKeeper;
class PlayerPainPartsKeeper;
class PlayerRecoverySafetyPoint;
class PlayerRippleGenerator;
class PlayerSeparateCapFlag;
class PlayerWetControl;
class PlayerStainControl;
class GaugeAir;
class WaterSurfaceShadow;
class WorldEndBorderKeeper;
class PlayerSeCtrl;

class PlayerStateWait;
class PlayerStateSquat;
class PlayerStateRunHakoniwa2D3D;
class PlayerStateSlope;
class PlayerStateRolling;
class PlayerStateSpinCap;
class PlayerStateJump;
class PlayerStateCapCatchPop;
class PlayerStateWallAir;
class PlayerStateWallCatch;
class PlayerStateGrabCeil;
class PlayerStatePoleClimb;
class PlayerStateHipDrop;
class PlayerStateHeadSliding;
class PlayerStateLongJump;
class PlayerStateFallHakoniwa;
class PlayerStateSandSink;
class ActorStateSandGeyser;
class PlayerStateRise;
class PlayerStateSwim;
class PlayerStateDamageLife;
class PlayerStateDamageSwim;
class PlayerStateDamageFire;
class PlayerStatePress;
class PlayerStateBind;
class PlayerStateHack;
class PlayerStateEndHack;
class PlayerStateCameraSubjective;
class PlayerStateAbyss;

class PlayerJudgeAirForceCount;
class PlayerJudgeCameraSubjective;
class PlayerJudgeCapCatchPop;
class PlayerJudgeDeadWipeStart;
class PlayerJudgeDirectRolling;
class PlayerJudgeEnableStandUp;
class PlayerJudgeForceLand;
class PlayerJudgeForceSlopeSlide;
class PlayerJudgeForceRolling;
class PlayerJudgeGrabCeil;
class PlayerJudgeInWater;
class PlayerJudgeInvalidateInputFall;
class PlayerJudgeLongFall;
class PlayerJudgeOutInWater;
class PlayerJudgeRecoveryLifeFast;
class PlayerJudgeSandSink;
class PlayerJudgeSpeedCheckFall;
class PlayerJudgeStartHipDrop;
class PlayerJudgeStartRise;
class PlayerJudgeStartRolling;
class PlayerJudgeStartRun;
class PlayerJudgeStartSquat;
class PlayerJudgeStartWaterSurfaceRun;
class PlayerJudgeSlopeSlide;
class PlayerJudgePoleClimb;
class PlayerJudgePreInputJump;
class PlayerJudgePreInputCapThrow;
class PlayerJudgePreInputHackAction;
class HackCapJudgePreInputHoveringJump;
class HackCapJudgePreInputSeparateThrow;
class HackCapJudgePreInputSeparateJump;
class PlayerJudgeWallCatch;
class PlayerJudgeWallCatchInputDir;
class PlayerJudgeWallHitDown;
class PlayerJudgeWallHitDownForceRun;
class PlayerJudgeWallHitDownRolling;
class PlayerJudgeWallKeep;

class PlayerActorHakoniwa : public PlayerActorBase, public IUseDimension {
public:
    PlayerActorHakoniwa(const char* name);
    void initPlayer(const al::ActorInitInfo& actorInitInfo,
                    const PlayerInitInfo& playerInitInfo) override;
    void updateModelShadowDropLength();
    void executeAfterCapTarget();
    void syncSensorAndCollision();
    void initAfterPlacement() override;
    void movement() override;
    void checkDamageFromCollision();
    void executePreMovementNerveChange();
    void control() override;
    void updateCarry();
    void updateCollider() override;
    bool isEnableDemo() override;
    bool isDamageStopDemo() const override;
    void startDemo() override;
    void setNerveOnGround();
    void endDemo() override;
    void startDemoPuppetable() override;
    void startPlayerPuppet();
    void cancelHackPlayerPuppetDemo();
    void endDemoPuppetable() override;
    void endPlayerPuppet();
    void startDemoShineGet() override;
    void endDemoShineGet() override;
    void startDemoMainShineGet() override;
    void endDemoMainShineGet() override;
    void startDemoHack() override;
    void endDemoHack() override;
    void startDemoKeepBind() override;
    void noticeDemoKeepBindExecute() override;
    void endDemoKeepBind() override;
    void startDemoKeepCarry() override;
    void endDemoKeepCarry() override;
    al::DemoActor* getDemoActor() override;
    PlayerAnimator* getDemoAnimator() override;
    PlayerPuppet* getPlayerPuppet() override;
    IUsePlayerCollision* getPlayerCollision() const override;
    u32 getPortNo() const override;
    void exeWait();
    bool tryActionCapReturn();
    bool tryActionCapSpinAttack();
    void exeSquat();
    bool tryActionSeparateCapThrow();
    void exeRun();
    void exeSlope();
    void exeRolling();
    void exeSpinCap();
    bool tryChangeNerveFromAir();
    bool tryActionCapSpinAttackMiss();
    void exeJump();
    void exeCapCatchPop();
    void exeWallAir();
    void exeWallCatch();
    void exeGrabCeil();
    void exePoleClimb();
    void exeHipDrop();
    void exeHeadSliding();
    __attribute__((noinline)) void exeLongJump();
    void exeFall();
    void exeSandSink();
    void exeSandGeyser();
    void exeRise();
    void exeSwim();
    void exeDamage();
    void exeDamageSwim();
    void exeDamageFire();
    void exePress();
    void exeHack();
    void exeEndHack();
    void exeBind();
    bool tryActionCapSpinAttackBindEnd();
    void exeDemo();
    void exeCamera();
    void exeAbyss();
    void exeDead();
    bool checkDeathArea() override;
    void sendCollisionMsg() override;
    void attackSensor(al::HitSensor* self, al::HitSensor* other) override;
    bool receiveMsg(const al::SensorMsg* message, al::HitSensor* other,
                    al::HitSensor* self) override;
    bool receivePushMsg(const al::SensorMsg* msg, al::HitSensor* other, al::HitSensor* self,
                        f32 maxPush) override;
    bool tryActionCapSpinAttackImpl(bool isNormal);
    PlayerHackKeeper* getPlayerHackKeeper() const override { return mHackKeeper; }
    PlayerInfo* getPlayerInfo() const override { return mInfo; }
    ActorDimensionKeeper* getActorDimensionKeeper() const override { return mDimensionKeeper; }

private:
    PlayerInfo* mInfo = nullptr;
    PlayerConst* mConst = nullptr;
    PlayerInput* mInput = nullptr;
    PlayerTrigger* mTrigger = nullptr;
    HackCap* mHackCap = nullptr;
    ActorDimensionKeeper* mDimensionKeeper = nullptr;
    PlayerModelHolder* mModelHolder = nullptr;
    PlayerModelChangerHakoniwa* mModelChanger = nullptr;
    PlayerAnimator* mAnimator = nullptr;
    PlayerColliderHakoniwa* mCollider = nullptr;
    PlayerPuppet* mPuppet = nullptr;
    PlayerAreaChecker* mAreaChecker = nullptr;
    al::WaterSurfaceFinder* mWaterSurfaceFinder = nullptr;
    PlayerOxygen* mOxygen = nullptr;
    PlayerDamageKeeper* mDamageKeeper = nullptr;
    PlayerDemoActionFlag* mDemoActionFlag = nullptr;
    PlayerCapActionHistory* mCapActionHistory = nullptr;
    PlayerCapManHeroEyesControl* mCapManHeroEyesControl = nullptr;
    PlayerContinuousJump* mContinuousJump = nullptr;
    PlayerContinuousLongJump* mContinuousLongJump = nullptr;
    PlayerCounterAfterUpperPunch* mCounterAfterUpperPunch = nullptr;
    PlayerCounterForceRun* mCounterForceRun = nullptr;
    PlayerCounterIceWater* mCounterIceWater = nullptr;
    PlayerCounterQuickTurnJump* mCounterQuickTurnJump = nullptr;
    PlayerWallActionHistory* mWallActionHistory = nullptr;
    PlayerBindKeeper* mBindKeeper = nullptr;
    PlayerCarryKeeper* mCarryKeeper = nullptr;
    PlayerEquipmentUser* mEquipmentUser = nullptr;
    PlayerHackKeeper* mHackKeeper = nullptr;
    PlayerFormSensorCollisionArranger* mFormSensorCollisionArranger = nullptr;
    PlayerJumpMessageRequest* mJumpMessageRequest = nullptr;
    PlayerSandSinkAffect* mSandSinkAffect = nullptr;
    PlayerSpinCapAttack* mSpinCapAttack = nullptr;
    PlayerActionDiveInWater* mActionDiveInWater = nullptr;
    PlayerEffect* mEffect = nullptr;
    PlayerEyeSensorHitHolder* mEyeSensorHitHolder = nullptr;
    PlayerPushReceiver* mPushReceiver = nullptr;
    PlayerHitPush* mHitPush = nullptr;
    PlayerExternalVelocity* mExternalVelocity = nullptr;
    PlayerJointControlKeeper* mJointControlKeeper = nullptr;
    PlayerPainPartsKeeper* mPainPartsKeeper = nullptr;
    PlayerRecoverySafetyPoint* mRecoverySafetyPoint = nullptr;
    PlayerRippleGenerator* mRippleGenerator = nullptr;
    PlayerSeparateCapFlag* mSeparateCapFlag = nullptr;
    PlayerWetControl* mWetControl = nullptr;
    PlayerStainControl* mStainControl = nullptr;
    al::FootPrintHolder* mFootPrintHolder = nullptr;
    GaugeAir* mGaugeAir = nullptr;
    WaterSurfaceShadow* mWaterSurfaceShadow = nullptr;
    WorldEndBorderKeeper* mWorldEndBorderKeeper = nullptr;
    al::ComboCounter* mComboCounter;
    PlayerSeCtrl* mSeCtrl = nullptr;
    al::HitSensor* mBodyHitSensor = nullptr;
    bool mIsLongShadow = false;
    PlayerStateWait* mStateWait = nullptr;
    PlayerStateSquat* mStateSquat = nullptr;
    PlayerStateRunHakoniwa2D3D* mStateRunHakoniwa2D3D = nullptr;
    PlayerStateSlope* mStateSlope = nullptr;
    PlayerStateRolling* mStateRolling = nullptr;
    PlayerStateSpinCap* mStateSpinCap = nullptr;
    PlayerStateJump* mStateJump = nullptr;
    PlayerStateCapCatchPop* mStateCapCatchPop = nullptr;
    PlayerStateWallAir* mStateWallAir = nullptr;
    PlayerStateWallCatch* mStateWallCatch = nullptr;
    PlayerStateGrabCeil* mStateGrabCeil = nullptr;
    PlayerStatePoleClimb* mStatePoleClimb = nullptr;
    PlayerStateHipDrop* mStateHipDrop = nullptr;
    PlayerStateHeadSliding* mStateHeadSliding = nullptr;
    PlayerStateLongJump* mStateLongJump = nullptr;
    PlayerStateFallHakoniwa* mStateFallHakoniwa = nullptr;
    PlayerStateSandSink* mStateSandSink = nullptr;
    ActorStateSandGeyser* mActorStateSandGeyser = nullptr;
    PlayerStateRise* mStateRise = nullptr;
    PlayerStateSwim* mStateSwim = nullptr;
    PlayerStateDamageLife* mStateDamageLife = nullptr;
    PlayerStateDamageSwim* mStateDamageSwim = nullptr;
    PlayerStateDamageFire* mStateDamageFire = nullptr;
    PlayerStatePress* mStatePress = nullptr;
    PlayerStateBind* mStateBind = nullptr;
    PlayerStateHack* mStateHack = nullptr;
    PlayerStateEndHack* mStateEndHack = nullptr;
    PlayerStateCameraSubjective* mStateCameraSubjective = nullptr;
    PlayerStateAbyss* mStateAbyss = nullptr;
    PlayerJudgeAirForceCount* mJudgeAirForceCount = nullptr;
    PlayerJudgeCameraSubjective* mJudgeCameraSubjective = nullptr;
    PlayerJudgeCapCatchPop* mJudgeCapCatchPop = nullptr;
    PlayerJudgeDeadWipeStart* mJudgeDeadWipeStart = nullptr;
    PlayerJudgeDirectRolling* mJudgeDirectRolling = nullptr;
    PlayerJudgeEnableStandUp* mJudgeEnableStandUp = nullptr;
    PlayerJudgeForceLand* mJudgeForceLand = nullptr;
    PlayerJudgeForceSlopeSlide* mJudgeForceSlopeSlide = nullptr;
    PlayerJudgeForceRolling* mJudgeForceRolling = nullptr;
    PlayerJudgeGrabCeil* mJudgeGrabCeil = nullptr;
    PlayerJudgeInWater* mJudgeInWater[4]{};
    PlayerJudgeInvalidateInputFall* mJudgeInvalidateInputFall = nullptr;
    PlayerJudgeLongFall* mJudgeLongFall = nullptr;
    PlayerJudgeOutInWater* mJudgeOutInWater = nullptr;
    PlayerJudgeRecoveryLifeFast* mJudgeRecoveryLifeFast = nullptr;
    PlayerJudgeSandSink* mJudgeSandSink = nullptr;
    PlayerJudgeSpeedCheckFall* mJudgeSpeedCheckFall = nullptr;
    PlayerJudgeStartHipDrop* mJudgeStartHipDrop = nullptr;
    PlayerJudgeStartRise* mJudgeStartRise = nullptr;
    PlayerJudgeStartRolling* mJudgeStartRolling = nullptr;
    PlayerJudgeStartRun* mJudgeStartRun = nullptr;
    PlayerJudgeStartSquat* mJudgeStartSquat = nullptr;
    PlayerJudgeStartWaterSurfaceRun* mJudgeStartWaterSurfaceRun = nullptr;
    PlayerJudgeSlopeSlide* mJudgeSlopeSlide = nullptr;
    PlayerJudgePoleClimb* mJudgePoleClimb = nullptr;
    PlayerJudgePreInputJump* mJudgePreInputJump = nullptr;
    PlayerJudgePreInputCapThrow* mJudgePreInputCapThrow = nullptr;
    PlayerJudgePreInputHackAction* mJudgePreInputHackAction = nullptr;
    HackCapJudgePreInputHoveringJump* mHackCapJudgePreInputHoveringJump = nullptr;
    HackCapJudgePreInputSeparateThrow* mHackCapJudgePreInputSeparateThrow = nullptr;
    HackCapJudgePreInputSeparateJump* mHackCapJudgePreInputSeparateJump = nullptr;
    PlayerJudgeWallCatch* mJudgeWallCatch = nullptr;
    PlayerJudgeWallCatchInputDir* mJudgeWallCatchInputDir = nullptr;
    PlayerJudgeWallHitDown* mJudgeWallHitDown = nullptr;
    PlayerJudgeWallHitDownForceRun* mJudgeWallHitDownForceRun = nullptr;
    PlayerJudgeWallHitDownRolling* mJudgeWallHitDownRolling = nullptr;
    PlayerJudgeWallKeep* mJudgeWallKeep = nullptr;
    bool mIsReduceOxygen = false;
};
static_assert(sizeof(PlayerActorHakoniwa) == 0x508);
